# Generated by Django 4.2.23 on 2025-07-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='head_teacher_classes',
            field=models.ManyToManyField(blank=True, related_name='head_teachers', to='classes.class'),
        ),
    ]
