# Generated by Django 4.2.23 on 2025-07-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'section', 'academic_year', 'school')},
        ),
    ]
