# Generated by Django 4.2.23 on 2025-07-24 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 24, 20, 39, 20, 619634, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
