# Generated by Django 4.2.23 on 2025-07-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('auto_backup', models.BooleanField(default=True)),
                ('session_timeout', models.PositiveIntegerField(default=30)),
                ('data_retention', models.PositiveIntegerField(default=365)),
                ('max_file_size', models.PositiveIntegerField(default=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('maintenance_bypass_users', models.TextField(blank=True, default='', help_text='Comma-separated usernames or emails allowed during maintenance mode.')),
            ],
        ),
    ]
