# Generated by Django 4.2.23 on 2025-06-27 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.student'),
        ),
    ]
