# Generated by Django 4.2.23 on 2025-07-05 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('classes', '0002_initial'),
        ('fees', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='students.student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='student_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.studentfee'),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feecategory'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='classes.class'),
        ),
        migrations.AddField(
            model_name='feereminder',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_reminders', to='students.student'),
        ),
        migrations.AddField(
            model_name='feereminder',
            name='student_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='fees.studentfee'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('class_obj', 'category', 'academic_year')},
        ),
    ]
