# Generated by Django 4.2.23 on 2025-07-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='structure',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('one_time', 'One Time')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fees.feestructure'),
        ),
    ]
