# Generated by Django 4.2.23 on 2025-07-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
        ('fees', '0004_studentfee_structure_alter_studentfee_fee_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='paid', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='studentfee',
            unique_together={('student', 'structure', 'due_date')},
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='paid_amount',
        ),
    ]
