# Generated by Django 4.2.23 on 2025-07-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_global_admin_room',
            field=models.BooleanField(default=False, help_text='Single shared room for all System Admins and School Admins'),
        ),
    ]
