# Generated by Django 4.2.23 on 2025-06-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
